//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muzik_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUZIK
    {
        public int MUZIKID { get; set; }
        public string SARKIADI { get; set; }
        public string ARTIST { get; set; }
        public string ALBUMADI { get; set; }
        public string SARKISURESI { get; set; }
        public Nullable<int> CIKISYILI { get; set; }
        public Nullable<int> TUR { get; set; }
    
        public virtual TBLTUR TBLTUR { get; set; }
    }
}
